// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmU1A5_1AL0uErC72iYmYqRDkGeE9Vkv8',
    appId: '1:1077131042154:web:7f938c87c2282e88065913',
    messagingSenderId: '1077131042154',
    projectId: 'tiktok-tutorial-10cb9',
    authDomain: 'tiktok-tutorial-10cb9.firebaseapp.com',
    storageBucket: 'tiktok-tutorial-10cb9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1S2B9VwZTD29c4RFNq8ZjnsLPkeTsCCU',
    appId: '1:1077131042154:android:544e947f4ecd98c2065913',
    messagingSenderId: '1077131042154',
    projectId: 'tiktok-tutorial-10cb9',
    storageBucket: 'tiktok-tutorial-10cb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzop5U9k-M_75bJnbP9PlXcObTuPiqc0g',
    appId: '1:1077131042154:ios:74ba0adc83fcbca9065913',
    messagingSenderId: '1077131042154',
    projectId: 'tiktok-tutorial-10cb9',
    storageBucket: 'tiktok-tutorial-10cb9.appspot.com',
    iosBundleId: 'com.example.tiktokFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzop5U9k-M_75bJnbP9PlXcObTuPiqc0g',
    appId: '1:1077131042154:ios:5aaf83c1b73f40aa065913',
    messagingSenderId: '1077131042154',
    projectId: 'tiktok-tutorial-10cb9',
    storageBucket: 'tiktok-tutorial-10cb9.appspot.com',
    iosBundleId: 'com.example.tiktokFlutter.RunnerTests',
  );
}
